using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using ClaudeAgentsShell.Application.Ports;

namespace ClaudeAgentsShell.Sessions.Hooks;

/// <summary>
/// Готовит файл настроек с хуками и сопровождающий его командный файл — оба в каталоге данных
/// приложения. В проект пользователя и в <c>~/.claude</c> не пишется ничего (раздел 7 CLAUDE.md).
/// <para>
/// Отправляет полезную нагрузку <c>curl.exe</c>: он есть в Windows 10 и 11 из коробки,
/// доустанавливать ничего не нужно, а запуск <c>powershell.exe</c> на каждый хук стоил бы
/// сотни миллисекунд. Команда завёрнута в <c>.cmd</c>, потому что хуки запускаются через
/// <c>cmd.exe</c>: там разворачивается <c>%ПЕРЕМЕННАЯ%</c> с токеном вкладки и там же
/// гарантируется тихий выход.
/// </para>
/// </summary>
public sealed class HookSettingsProvider : IHookSettingsProvider
{
    /// <summary>Имя генерируемого файла настроек; передаётся <c>claude</c> через <c>--settings</c>.</summary>
    public const string SettingsFileName = "hook-settings.json";

    /// <summary>Имя командного файла, который вызывается из каждого хука.</summary>
    public const string ScriptFileName = "hook-send.cmd";

    private const string TempSuffix = ".tmp";

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private readonly IAppDataPaths _paths;

    /// <inheritdoc cref="HookSettingsProvider" />
    public HookSettingsProvider(IAppDataPaths paths)
    {
        ArgumentNullException.ThrowIfNull(paths);
        _paths = paths;
    }

    /// <inheritdoc />
    public string TokenVariableName => HookProtocol.TokenVariableName;

    /// <inheritdoc />
    public async Task<string> EnsureSettingsFileAsync(Uri endpoint, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(endpoint);

        // Обращение к AppData создаёт каталог данных, если его ещё нет.
        var directory = _paths.AppData;
        var script = Path.Combine(directory, ScriptFileName);
        var settings = Path.Combine(directory, SettingsFileName);

        // Оба файла пишутся через временный: сессия могла открыть прежний по --settings,
        // и надорванный файл хуже устаревшего.
        await WriteAtomicAsync(script, BuildScript(endpoint), cancellationToken).ConfigureAwait(false);
        await WriteAtomicAsync(settings, BuildSettings(script), cancellationToken).ConfigureAwait(false);

        return settings;
    }

    /// <summary>
    /// Командный файл: читает полезную нагрузку хука со stdin и отправляет её приёмнику.
    /// Ничего не печатает и всегда завершается нулём — иначе <c>Stop</c> не дал бы агенту
    /// остановиться, а вывод <c>SessionStart</c> уехал бы в контекст модели.
    /// </summary>
    private static string BuildScript(Uri endpoint)
    {
        var builder = new StringBuilder();
        builder.Append("@echo off\r\n");
        builder.Append("rem Generated by Claude Agents Shell. Sends the hook payload to the running app.\r\n");
        builder.Append("rem Rewritten on every start: the listener port changes.\r\n");
        // --noproxy обязателен: HTTP_PROXY в окружении пользователя увёл бы вызов к самому себе
        // через прокси, и маркеры состояния пропали бы молча.
        builder.Append("curl.exe -s -o nul --max-time 3 --noproxy \"*\"");
        builder.Append(" -H \"Content-Type: application/json\"");
        builder.Append($" -H \"{HookProtocol.TokenHeaderName}: %{HookProtocol.TokenVariableName}%\"");
        builder.Append(" --data-binary @- \"");
        builder.Append(endpoint.AbsoluteUri.TrimEnd('/'));
        builder.Append("\" 2>nul\r\n");
        builder.Append("exit /b 0\r\n");
        return builder.ToString();
    }

    private static string BuildSettings(string scriptPath)
    {
        // Путь берётся в кавычки всегда: cmd понимает такую команду и с пробелами в пути, и без них.
        var command = new HookCommandDto
        {
            Type = "command",
            Command = $"\"{scriptPath}\"",
            Timeout = 5,
        };

        var matcher = new HookMatcherDto { Hooks = [command] };
        var document = new HookSettingsDto
        {
            // Семь зарегистрированных хуков: начало и конец сессии, отправка промпта, конец хода
            // агента в двух видах (штатный и оборванный) и пара хуков сабагентов. Состояние
            // вкладки выводится только из них (раздел 7 CLAUDE.md), но набором всех хуков
            // Claude Code они не являются: тот же Notification с notification_type
            // (permission_prompt, idle_prompt, agent_needs_input) означал бы настоящее ожидание
            // человека. Он сознательно не регистрируется — это отдельное решение пользователя.
            // Имена точные: незнакомое имя Claude Code молча пропустит, и вкладка останется
            // без маркера.
            // Матчер у SessionStart не сужается до отдельных source: сжатие контекста приходит
            // тем же хуком, и решение «это не граница хода» принимает координатор. Получить
            // событие и осознанно ничего не сделать надёжнее, чем его не увидеть.
            Hooks = new Dictionary<string, List<HookMatcherDto>>(StringComparer.Ordinal)
            {
                ["SessionStart"] = [matcher],
                ["UserPromptSubmit"] = [matcher],
                ["Stop"] = [matcher],
                ["StopFailure"] = [matcher],
                ["SubagentStart"] = [matcher],
                ["SubagentStop"] = [matcher],
                ["SessionEnd"] = [matcher],
            },
        };

        return JsonSerializer.Serialize(document, SerializerOptions);
    }

    private static async Task WriteAtomicAsync(string path, string content, CancellationToken cancellationToken)
    {
        var temporary = path + TempSuffix;
        await File.WriteAllTextAsync(temporary, content, new UTF8Encoding(false), cancellationToken).ConfigureAwait(false);
        File.Move(temporary, path, overwrite: true);
    }

    private sealed class HookSettingsDto
    {
        [JsonPropertyName("hooks")]
        public Dictionary<string, List<HookMatcherDto>> Hooks { get; set; } = new(StringComparer.Ordinal);
    }

    private sealed class HookMatcherDto
    {
        [JsonPropertyName("hooks")]
        public List<HookCommandDto> Hooks { get; set; } = [];
    }

    private sealed class HookCommandDto
    {
        [JsonPropertyName("type")]
        public string Type { get; set; } = "command";

        [JsonPropertyName("command")]
        public string Command { get; set; } = string.Empty;

        [JsonPropertyName("timeout")]
        public int Timeout { get; set; }
    }
}
