<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ClaudeAgentsShell.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaudeAgentsShell.Domain\ClaudeAgentsShell.Domain.csproj" />
  </ItemGroup>

</Project>
